import fs from "fs";
import path from "path";
import { pathToFileURL } from "url";

import { countCountedStepsInLessonStepsExcludingAdvanced } from "../src/lesson-core/stepCountUtils";

type LessonSteps = Record<number, any>;

function pickLessonSteps(mod: any, moduleNameForErrors: string): LessonSteps {
  const candidate =
    mod?.LESSON_STEPS_BEGINNER ??
    mod?.LESSON_STEPS_INTERMEDIATE ??
    mod?.LESSON_STEPS_ADVANCED ??
    mod?.LESSON_STEPS_CIRCUIT_BEG ??
    mod?.LESSON_STEPS_CIRCUIT_INT ??
    mod?.LESSON_STEPS_CIRCUIT_ADV ??
    mod?.LESSON_STEPS;

  if (!candidate || typeof candidate !== "object") {
    throw new Error(
      `[generateLessonTotals] Missing step export in ${moduleNameForErrors}. ` +
        `Expected LESSON_STEPS_BEGINNER / INTERMEDIATE / ADVANCED / CIRCUIT_* / LESSON_STEPS`
    );
  }
  return candidate as LessonSteps;
}

function computeLessonTotal(lessonSteps: LessonSteps): number {
  const total = countCountedStepsInLessonStepsExcludingAdvanced(lessonSteps);
  return Number.isFinite(total) ? Math.max(0, total) : 0;
}

function fileBaseToLessonSlug(base: string): string {
  // codeBeg -> code-beg, circuitInt -> circuit-int
  return base.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function isTargetLessonFile(filename: string): boolean {
  if (!/\.(ts|tsx)$/.test(filename)) return false;
  if (filename.includes(".steps.")) return false;
  if (filename.includes(".test.")) return false;
  if (filename.startsWith("generated")) return false;

  // IMPORTANT: only lesson modules, not helper components
  return /^(code|circuit)[A-Z].*\.(ts|tsx)$/.test(filename);
}

async function importModuleFromAbs(absPath: string) {
  const url = pathToFileURL(absPath).href;
  return import(url);
}

async function main() {
  const projectsDir = path.join(process.cwd(), "src", "projects");

  // We'll generate into lesson-core so your existing imports keep working:
  const outPath = path.join(process.cwd(), "src", "lesson-core", "generatedLessonTotals.ts");

  const projectSlugs = fs
    .readdirSync(projectsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  const generatedLessonTotals: Record<string, Record<string, number>> = {};

  for (const projectSlug of projectSlugs) {
    const lessonsDir = path.join(projectsDir, projectSlug, "lessons");
    if (!fs.existsSync(lessonsDir)) continue;

    const lessonFiles = fs.readdirSync(lessonsDir).filter(isTargetLessonFile);
    if (lessonFiles.length === 0) continue;

    const lessonTotals: Record<string, number> = {};

    for (const filename of lessonFiles) {
      const abs = path.join(lessonsDir, filename);
      const base = filename.replace(/\.(ts|tsx)$/, "");
      const lessonSlug = fileBaseToLessonSlug(base);

      const mod = await importModuleFromAbs(abs);
      const stepsObj = pickLessonSteps(mod, `${projectSlug}/lessons/${base}`);
      lessonTotals[lessonSlug] = computeLessonTotal(stepsObj);
    }

    generatedLessonTotals[projectSlug] = lessonTotals;
  }

  const generatedProjectTotals: Record<string, number> = {};
  for (const projectSlug of Object.keys(generatedLessonTotals)) {
    generatedProjectTotals[projectSlug] = Object.values(generatedLessonTotals[projectSlug]).reduce((a, b) => a + b, 0);
  }

  const fileContents = `/**
 * AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by scripts/generateLessonTotals.ts
 *
 * Server-safe: exports ONLY plain numbers.
 */

export const GENERATED_LESSON_TOTALS = ${JSON.stringify(generatedLessonTotals, null, 2)} as const;

export const GENERATED_PROJECT_TOTALS = ${JSON.stringify(generatedProjectTotals, null, 2)} as const;
`;

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, fileContents, "utf8");

  console.log(`[generateLessonTotals] Wrote: ${outPath}`);
  console.log(`[generateLessonTotals] Projects generated: ${Object.keys(generatedLessonTotals).length}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});