// src/lesson-core/projectStepRegistry.ts
/**
 * Registry of project lesson totals for computing TOTAL steps on the server
 * (admin progress, dashboards across devices, etc).
 *
 * Goal: Admin percent must match Dashboard percent:
 *   percent = round(stepsDone / totalSteps * 100)
 *
 * Dashboard "default" totals behavior matches CodeLessonBase when advancedUnlocked=false:
 * - excludes optional lessons
 * - excludes optional steps
 * - excludes advanced lessons (locked)
 *
 * IMPORTANT:
 * - This file must be server-safe (no "use client" imports).
 * - Totals are generated by scripts/generateLessonTotals.ts into generatedLessonTotals.ts
 * - Do NOT silently return 0 when a registry entry is missing — that causes 0% everywhere.
 */

import { GENERATED_LESSON_TOTALS, GENERATED_PROJECT_TOTALS } from "./generatedLessonTotals";

type LessonTotalsByProject = Record<string, Record<string, number>>;

// Cast to a looser type for runtime lookup convenience.
const LESSON_SLUG_TO_TOTALS: LessonTotalsByProject = GENERATED_LESSON_TOTALS as any;

const FALLBACK_TOTALS_BY_PROJECT: Record<string, number> = {
  // Use only as a LAST resort if generated totals are missing.
  // You can keep this, but ideally GENERATED_PROJECT_TOTALS covers everything.
  "electric-status-board": 283,
};

/** Extract level suffix from lesson slug (code-beg -> beg, circuit-int -> int). */
export function levelFromLessonSlug(lessonSlug: string | null | undefined): "beg" | "int" | "adv" {
  const last = (lessonSlug || "").split("/").pop() || "";
  const parts = last.split(/[-_]/g).filter(Boolean);
  const suffix = (parts[parts.length - 1] || "").toLowerCase();

  if (suffix === "beg" || suffix === "beginner") return "beg";
  if (suffix === "int" || suffix === "intermediate") return "int";
  if (suffix === "adv" || suffix === "advanced") return "adv";
  return "beg";
}

/**
 * Total steps for a single lesson slug (e.g., code-beg or circuit-int),
 * using precomputed totals (generated).
 */
export function getTotalForLessonSlug(projectSlug: string, lessonSlug: string): number {
  const byProject = LESSON_SLUG_TO_TOTALS[projectSlug];

  if (process.env.NODE_ENV === "development") {
    // eslint-disable-next-line no-console
    console.log("──────── DEBUG getTotalForLessonSlug ────────");
    // eslint-disable-next-line no-console
    console.log("projectSlug:", projectSlug);
    // eslint-disable-next-line no-console
    console.log("lessonSlug:", lessonSlug);
    // eslint-disable-next-line no-console
    console.log("Known projects:", Object.keys(LESSON_SLUG_TO_TOTALS));
  }

  if (!byProject) {
    if (process.env.NODE_ENV === "development") {
      // eslint-disable-next-line no-console
      console.error(`[projectStepRegistry] Unknown projectSlug: ${projectSlug}`);
    }
    return (
      (GENERATED_PROJECT_TOTALS as any)[projectSlug] ??
      FALLBACK_TOTALS_BY_PROJECT[projectSlug] ??
      0
    );
  }

  if (process.env.NODE_ENV === "development") {
    // eslint-disable-next-line no-console
    console.log("Available lesson keys for project:", Object.keys(byProject));
  }

  const total = byProject[lessonSlug];

  if (typeof total !== "number" || !Number.isFinite(total)) {
    if (process.env.NODE_ENV === "development") {
      // eslint-disable-next-line no-console
      console.error(
        `[projectStepRegistry] Missing/invalid total for project=${projectSlug} lessonSlug=${lessonSlug}. ` +
          `Available: ${Object.keys(byProject).join(", ")}`
      );
    }
    return 0;
  }

  if (process.env.NODE_ENV === "development") {
    // eslint-disable-next-line no-console
    console.log("Computed total (generated):", total);
    // eslint-disable-next-line no-console
    console.log("──────── END DEBUG ────────");
  }

  return Math.max(0, total);
}

/**
 * Totals for a project at a given level (code-{level} + circuit-{level}),
 * matching the Dashboard’s percent denominator.
 *
 * NOTE: some projects may not have circuit-adv; we treat missing lessons as 0.
 */
export function getTotalsForProjectLevel(projectSlug: string, level: "beg" | "int" | "adv") {
  const codeSlug = `code-${level}`;
  const circuitSlug = `circuit-${level}`;

  const codeTotal = getTotalForLessonSlug(projectSlug, codeSlug);
  const circuitTotal = getTotalForLessonSlug(projectSlug, circuitSlug);

  return {
    codeTotal,
    circuitTotal,
    total: Math.max(0, codeTotal + circuitTotal),
    codeSlug,
    circuitSlug,
  };
}

/**
 * Total steps for an entire project across all generated lesson totals.
 */
export function getProjectTotalSteps(projectSlug: string): number {
  const byProject = LESSON_SLUG_TO_TOTALS[projectSlug];

  if (!byProject) {
    return (
      (GENERATED_PROJECT_TOTALS as any)[projectSlug] ??
      FALLBACK_TOTALS_BY_PROJECT[projectSlug] ??
      0
    );
  }

  // Sum all lesson totals for this project
  const total = Object.values(byProject).reduce((acc, n) => acc + (Number.isFinite(n) ? n : 0), 0);

  if (total > 0) return total;

  return (
    (GENERATED_PROJECT_TOTALS as any)[projectSlug] ??
    FALLBACK_TOTALS_BY_PROJECT[projectSlug] ??
    0
  );
}